name: fwfh_just_audio
version: 0.9.0+3
description: WidgetFactory extension to render AUDIO with the just_audio plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
publish_to: "none"

environment:
  flutter: ">=3.7.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_widget_from_html_core:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/core
      ref: master

  just_audio: ">=0.9.0 <0.10.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  just_audio_platform_interface: ">=4.0.0 <5.0.0"
  lint: any
  tuple: any

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - fwfh
