name: fwfh_cached_network_image
version: 0.7.0+5
description: WidgetFactory extension to render IMG with cached_network_image plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
publish_to: none

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  cached_network_image:
    git:
      url: https://github.com/tentram/flutter_cached_network_image
      path: cached_network_image
      ref: develop

  flutter:
    sdk: flutter

  flutter_cache_manager:
    git:
      url: https://github.com/tentram/flutter_cache_manager
      path: flutter_cache_manager
      ref: develop

  flutter_widget_from_html_core:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/core

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  lint: any
  mocktail: ^1.0.0
