name: fwfh_chewie
version: 1.0.0
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  chewie:
    git:
      url: https://github.com/tentram/chewie
      ref: master
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.8.0 <0.11.0"
  video_player: ^2.6.1

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  plugin_platform_interface: any
  video_player_platform_interface: ">=5.0.0 <7.0.0"
