name: flutter_widget_from_html
version: 0.10.2
description: Flutter package to render html as widgets that supports hyperlink, image, audio, video, iframe and many other tags.
homepage: https://github.com/daohoangson/flutter_widget_from_html
publish_to: none

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_widget_from_html_core:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/core

  fwfh_cached_network_image:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/fwfh_cached_network_image

  fwfh_chewie:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/fwfh_chewie

  fwfh_just_audio:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/fwfh_just_audio

  fwfh_svg:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/fwfh_svg

  fwfh_url_launcher:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/fwfh_url_launcher

  fwfh_webview:
    git:
      url: https://github.com/tentram/flutter_widget_from_html
      path: packages/fwfh_webview

  html: ^0.15.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_cached_network_image:
    path: ../fwfh_cached_network_image
  fwfh_chewie:
    path: ../fwfh_chewie
  fwfh_just_audio:
    path: ../fwfh_just_audio
  fwfh_svg:
    path: ../fwfh_svg
  fwfh_text_style:
    path: ../fwfh_text_style
  fwfh_url_launcher:
    path: ../fwfh_url_launcher
  fwfh_webview:
    path: ../fwfh_webview

dev_dependencies:
  file:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  lint: any
  mocktail: ^1.0.0

flutter:
  assets:
    - test/images/
